checksumBehavior: ignore

compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-outdated.cjs
    spec: "https://mskelton.dev/yarn-outdated/v2"

yarnPath: .yarn/releases/yarn-4.5.3-git.20241125.hash-8bfe2d5.cjs
